### ISSUE TITLE
Demande d'info

### ISSUE THREAD

**Issue by alx68** [KiboOst/php-simpleNetatmoAPI#10]
Bonjour, @KiboOst 

Je cherche a faire fonctionner ce script sur jeedom mais je ne comprend pas comment faire.
J'ai cherche sur le forum mais rien vu de probant ?.
Aurait tu un lien vers un tuto ou autre ?

Merci pour ton retour.

**Comment by skyynet** [comment]
See http://skyynet.de/e-netatmo

**Comment by KiboOst** [comment]
Bonjour,

Tout dépend de ce que tu veux faire. Avec le plugin script, tu peut créer des actions et/ou info, qui pointent vers un fichier php à toi qui s'appuie sur cette API. Ce n'est qu'un exemple.

Demande peu-être sur https://community.jeedom.com/ ?
