### ISSUE TITLE
Ask question about authorization

### ISSUE THREAD

**Issue by loicdeschamps** [KiboOst/php-simpleNetatmoAPI#11]
Hi

Is script is valid with the new authorisation  of netatmo (begin oct 2022) ?

Regards

Bonjour

Est ce que ce script va fonctionner avec la nouvelle api d'authorisation imposé par netatmo en octobre 2022 ?

Cordialement

**Comment by KiboOst** [comment]
Hi,
Didn't tested yet, but as I use it everyday automatically with Jeedom I will definitely try to ...

**Comment by loicdeschamps** [comment]
Merci

**Comment by guldi3** [comment]
Hi,
I'm not able to register a webhook. I lost my existing connection in the last month and I tried to reregister it. The answer from Netatmo Api ist "﻿﻿Can't connect to Netatmo Server."...

I think, there is a new authentication way befor a webhook can be registered.
