### ISSUE TITLE
Can't connect to Netatmo Server

### ISSUE THREAD

**Issue by ghost** [KiboOst/php-simpleNetatmoAPI#15]
I get this error direct after initialising. Just at testing to connect.

So splNetatmoAPI.php is found and included. I have entered variables for Netatmo_user, pass, id and secret in front of the initial $_splNetatmo = new splNetatmoAPI call.

ID and Secret is newly created at Netatmo Server.
What do I wrong?

**Comment by loicdeschamps** [comment]
same issue since 2 weeks
i use web server on synology

**Comment by loicdeschamps** [comment]
Réponse a moi même
Netatmo a changé la façon de se connecter. Il faut utiliser le refresh token
require('./splNetatmoAPI.php');
$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, $refreshtoken);

**Comment by Tuxx-dev** [comment]
> Réponse a moi même Netatmo a changé la façon de se connecter. Il faut utiliser le refresh token require('./splNetatmoAPI.php'); $_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, $refreshtoken);

Merci pour le tips j'ai pu adapté mon système :-)
