### ISSUE TITLE
De nouveau Can't connect to Netatmo Server

### ISSUE THREAD

**Issue by Cadkey** [KiboOst/php-simpleNetatmoAPI#16]
L'authentification Netatmo a encore changé.
Il semble que le access token ait une durée de vie de 3 heures et qu'il faille le recuperer et le stocker pour l'utiliser (toutes les 3 heures).
La solution serait ici: https://github.com/philippelt/netatmo-api-python
Mais je n'ai pas reussi à recuperer le nouvel acces token. :(
je n'ai pas compris la procédure à priori.

**Comment by KiboOst** [comment]
Oui j'ai vue çà, pas bcp de temps en ce moment et je commence à penser à virer tout netatmo, çà devient trop fermé et inutilisable dans un environnement de maison connectée...

**Comment by Cadkey** [comment]
C’est pénible. J’ai pas mal de produit Netatmo, dont des prises Legrand Netatmo que j’ai installé il y a moins de 6 mois.
Je recherche de mon côté comment récupérer l’accesstoken renouvellé.

**Comment by KiboOst** [comment]
J'ai un truc qui fonctionne, il faut que je fasse d'autres tests et que je mette à jour la doc, mais tout est fonctionnel.

**Comment by Cadkey** [comment]
Super, merci à toi. Je récupère dès que c'est dispo. 👍

**Comment by KiboOst** [comment]
Normalement c'est bon, voir la doc dans requirements, j'ai mis en place sur mon Jeedom et tout est reparti.

**Comment by dedelajoie** [comment]
Bonjour, 
j'ai une erreur "Can't connect to Netatmo Server" avec cette nouvelle version. 

Pourtant mon fichier est simplissime ($Netatmo_app_id et $Netatmo_app_secret correspondent Client_ID et Client_secret trouvés sur la page de mon application) :

```
<?php
require($_SERVER['DOCUMENT_ROOT']."class/splNetatmoAPI.php");
$Netatmo_app_id='XXXXXXXXXXX';
$Netatmo_app_secret='XXXXXXXX';
$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, 1);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);
?>

```

je suis sous PHP 7.4.3-4ubuntu2.19 
une idée ?

**Comment by TiSiAi** [comment]
Bonsoir
Merci pour le taff, c'est OK pour ma part, sauf que j'ai du désactiver 2 lignes dans le constructeur de la classe
Je n'ai pas de Cameras et du coup, je me prends une erreur avec le getCamerasDatas qui se déclenche :
$this->error = 'Unfound home with ID '.$this->_homeID; 

J'ai désactivé à l'arrache le getCameras() et le getPersons() vue que je n'avais besoin que de la météo mais je préfère te remonter le soucis si besoin ;)

Merci encore

Code désactivé dans le constructeur
$this->_homeID = $homeID;
$var = $this->connect();
if ($var == true)
{
    $this->getWeatherDatas();
    **//$this->getCameras();
    //$this->getPersons();**
}

**Comment by TiSiAi** [comment]
> Bonjour, j'ai une erreur "Can't connect to Netatmo Server" avec cette nouvelle version.
> 
> Pourtant mon fichier est simplissime ($Netatmo_app_id et $Netatmo_app_secret correspondent Client_ID et Client_secret trouvés sur la page de mon application) :
> 
> ```
> <?php
> require($_SERVER['DOCUMENT_ROOT']."class/splNetatmoAPI.php");
> $Netatmo_app_id='XXXXXXXXXXX';
> $Netatmo_app_secret='XXXXXXXX';
> $_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, 1);
> if (isset($_splNetatmo->error)) die($_splNetatmo->error);
> ?>
> ```
> 
> je suis sous PHP 7.4.3-4ubuntu2.19 une idée ?

Bonsoir 
Tu as bien crée le fichier refreshtoken.txt et mis dedans le refreshtoken généré une première fois depuis l'interface Netatmo ?
Pas de soucis de mon coté jusque la

**Comment by dedelajoie** [comment]
oui oui bien sur 
et il est en 666 aucazou

**Comment by TiSiAi** [comment]
> oui oui bien sur
> et il est en 666 aucazou

ok, c'était au cas où ...

**Comment by Cadkey** [comment]
> $this->error = 'Unfound home with ID '.$this->_homeID;

TiSiAi, tu as cette erreur car tu dois encore  appeler l'api en passant le refreshtoken en dernier argument.
$_splNetatmo = new splNetatmoAPI(, $Netatmo_app_id, $Netatmo_app_secret, $refreshtoken);
alors qu'il faut uniquement ceci:
$_splNetatmo = new splNetatmoAPI(, $Netatmo_app_id, $Netatmo_app_secret);
Le $refreshtoken est geré par l'api.
Du coup ton argument en trop va se coller dans le prochain $this donc $this->_homeID = $homeID. Et ton $homeID prend la valeur de $refreshtoken que tu as envoyé... Ca fonctionne tout de suite moins bien ;)
L'api de KiboOst est nickel, rien à modifier.

**Comment by Cadkey** [comment]
> j'ai une erreur "Can't connect to Netatmo Server" avec cette nouvelle version.

Dans l'API as-tu changé la ligne protected $tokenFilePath = 'refreshtoken.txt' avec le bon path, par exemple
protected $tokenFilePath = '/volume1/script/refreshtoken.txt'; si tu as créé le fichier refreshtoken.txt dans /volume1/script
C'est tout.

**Comment by TiSiAi** [comment]
> > $this->error = 'Unfound home with ID '.$this->_homeID;
> 
> TiSiAi, tu as cette erreur car tu dois encore appeler l'api en passant le refreshtoken en dernier argument. $_splNetatmo = new splNetatmoAPI(, $Netatmo_app_id, $Netatmo_app_secret, $refreshtoken); alors qu'il faut uniquement ceci: $_splNetatmo = new splNetatmoAPI(, $Netatmo_app_id, $Netatmo_app_secret); Le $refreshtoken est geré par l'api. Du coup ton argument en trop va se coller dans le prochain $this donc $this->_homeID = $homeID. Et ton $homeID prend la valeur de $refreshtoken que tu as envoyé... Ca fonctionne tout de suite moins bien ;) L'api de KiboOst est nickel, rien à modifier.

Non, j'utilise bien cette méthode:
```
require($_SERVER['DOCUMENT_ROOT']."/HCWeb/splNetatmoAPI.php");
$_splNetatmo = new splNetatmoAPI($app_id, $app_secret);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);

```

**Comment by Semabeba** [comment]
> Oui j'ai vue çà, pas bcp de temps en ce moment et je commence à penser à virer tout netatmo, çà devient trop fermé et inutilisable dans un environnement de maison connectée...

Bonjour @KiboOst , pour moi, ça fonctionne, nickel. Merci pour le partage.
J'ai une question, concernant la pression. Comment on peu l'obtenir, stp?
D'avance, merci

**Comment by Cadkey** [comment]
> J'ai une question, concernant la pression. Comment on peu l'obtenir, stp? D'avance, merci

$getWeatherStationDatas = $_splNetatmo->getWeatherStationDatas();
$pressure = $getWeatherStationDatas['Pressure'];

**Comment by Semabeba** [comment]
> > J'ai une question, concernant la pression. Comment on peu l'obtenir, stp? D'avance, merci
> 
> $getWeatherStationDatas = $_splNetatmo->getWeatherStationDatas(); $pressure = $getWeatherStationDatas['Pressure'];

@Cadkey Merci pour la réponse. Ca fonctionne avec votre code, mais malheureusement je ne sais pas utiliser la script, car elle fonctionne uniquement si on la lance manuellement (pas possible via cron jobs)
