### ISSUE TITLE
authentification Netatmo modifié depuis hier midi

### ISSUE THREAD

**Issue by Cadkey** [KiboOst/php-simpleNetatmoAPI#18]
J'ai tenté de solutionner.
Je stocke access_token et refresh_token dans un json. La Doc dit que la durée de vie est de 3h mais je constate que le couple access_token refresh_token ne fonctionne qu'une fois et génère quand même des erreurs régulièrement.

**Comment by Cadkey** [comment]
Personne d'autre n'a constaté un changement dans l'authentification ?

**Comment by hax1** [comment]
you can fix it by replacing lines 791-798 with:

$jsonContent = file_get_contents($this->tokenFilePath);

if ($jsonContent === false) {
    throw new Exception("Unable to read the token file.");
}

$tokens = json_decode($jsonContent, true);

if ($tokens === null && json_last_error() !== JSON_ERROR_NONE) {
    throw new Exception("JSON decoding error: " . json_last_error_msg());
}

$this->_access_token = $tokens['_access_token'] ?? null;
$this->_refresh_token = $tokens['_refresh_token'] ?? null;

if ($this->_access_token === null || $this->_refresh_token === null) {
    throw new Exception("Access token or refresh token not found in the JSON file.");
}

// end of replacing

and putting the tokens into refreshtoken.txt in json format like:

{
  "_access_token": "ACCESS_TOKEN_FROM_NETATMO_HERE",
  "_refresh_token": "REFRESH_TOKEN_FROM_NETATMO_HERE"
}

**Comment by hax1** [comment]
also replace line 772 with:

        $tokens = [
    '_access_token' => $jsonDatas['access_token'],
    '_refresh_token' => $jsonDatas['refresh_token']
        ];
        $jsonData = json_encode($tokens);
        $result = file_put_contents($this->tokenFilePath, $jsonData);

**Comment by Cadkey** [comment]
@hax1 Thanks for your help.
The tokens change with each API call, even though they are supposed to have a lifespan of 3 hours?

**Comment by hax1** [comment]
@Cadkey only the refreshtoken I guess, but with the modifications it seems to work anyway.

**Comment by Cadkey** [comment]
@hax1 on my synology with your changes, both tokens change access_token and refresh_token on every API call.
That's what surprises me.
I made a similar modification with the same observation.
Can you confirm that the authentication has changed a few days ago or nothing has changed?

**Comment by loicdeschamps** [comment]
meme probleme d'authentification pour moi - le refesh_tocken ne fonctionne qu'une fois également

**Comment by hax1** [comment]
adapt the code as I wrote above, works fine for me.

if the original author wants I can make a pull request @KiboOst

**Comment by Cadkey** [comment]
@hax1 Your modification works
In my case, refresh_token changes on each request. Before this was not the case.
I agree with @loicdeschamps

**Comment by loicdeschamps** [comment]
![image](https://github.com/KiboOst/php-simpleNetatmoAPI/assets/113504040/99c33f4d-a04d-4229-b6e1-30fb0e442c30)

Est ce le bon format du fichier refreshtoken.txt ?

**Comment by Cadkey** [comment]
Au final, j'ai fait la modif mais il s'avère que sans rien modifier ça refonctionne chez moi. Il faut juste régénèrer un acces_token et un refresh_token' sur la page netatmo et coller le refresh_token dans ton fichier comme la première fois. Je suppose qu'il y a eu une interruption de service qui a invalidé les token. Ma situation semble être similaire à la tienne. Il n'y a pas de discussion sur le net validant une modif sauvage côté netatmo.

In the end, I made the modification but without modifying anything it works again for me.  You just have to regenerate an acces_token and a refresh_token' on the netatmo page and paste the refresh_token in your file like the first time.  I assume there was a service problem that invalidated the tokens.  My situation seems to be similar to yours.  There is no discussion on the net validating a modification on the netatmo side.

**Comment by hax1** [comment]
guys, I know you like french, and my mother tongue is german. but still, on the internet use english ... mkay?

**Comment by dedelajoie** [comment]
I do like french and my mother tongue is french too :) and it unfortunately doesn't work for me even in english . 

I 
-modified the lines in splNetatmoAPI.php  according to your instructions 
- placed a refreshtoken.txt file in the folder where I call the splNetatmoAPI.php  
- regenerate a set of _acces_token and refresh_token and copy/paste them in the refreshtoken.txt 
- changed this file to 666

but I got : 
`
Warning: file_get_contents(https://api.netatmo.net//api/gethomedata?access_token=XXXX|XXXX&size=50): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /var/www/html/NetatmoStuff/php-simpleNetatmoAPI-master/class/splNetatmoAPI.php on line 565

Warning: file_get_contents(https://api.netatmo.net//api/gethomedata?access_token=XXXX|XXXX&size=50): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /var/www/html/NetatmoStuff/php-simpleNetatmoAPI-master/class/splNetatmoAPI.php on line 565
Unfound home with ID 0
`

Never heard too about this "home with ID 0"

does anyone has an idea ?
thanks in advance and thank you again for your work

**Comment by Cadkey** [comment]
did you regenerate your token on the netatmo site and paste refresh_token in the txt file like the  first time?  This is the solution for me, nothing else.

**Comment by loicdeschamps** [comment]
now i have this message : Unfound home with ID

**Comment by dedelajoie** [comment]
@Cadkey oh yes ! every time I try :( 
@loicdeschamps same here !

**Comment by Cadkey** [comment]
error at what line number?

**Comment by dedelajoie** [comment]
her it says line 565 : 
Warning: file_get_contents(https://api.netatmo.net//api/gethomedata?access_token=XXX|XXX&size=50): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in /var/www/html/dash5.13/splNetatmoAPI.php on line 565

**Comment by Cadkey** [comment]
Ok, I don't use a camera.  I don't use this part of the API.

**Comment by dedelajoie** [comment]
neither do I 

look here is the code of my php file : 

```
<?php 
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require($_SERVER['DOCUMENT_ROOT'].'/dash5.13/splNetatmoAPI.php');

echo "1";
$Netatmo_app_id = 'XXX';
$Netatmo_app_secret = 'XXXX';
echo "2";

$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);

$getWeatherModuleDatas = $_splNetatmo->getWeatherModuleDatas('Exterieur');
echo "<pre>getWeatherModuleDatas:<br>".json_encode($getWeatherModuleDatas, JSON_PRETTY_PRINT)."</pre><br>";
echo "fini";
?>
```

and yes splNetatmoAPI.php is in this directory
and there si too refreshtoken.txt

**Comment by loicdeschamps** [comment]
i use in web server


```
<?php
$Netatmo_user = 'xxxx@gmail.com';
$Netatmo_pass = 'yyyyyyy';
$Netatmo_app_id = 'yyyyyy';
$Netatmo_app_secret= 'zzzzzzzzz';

require($_SERVER['DOCUMENT_ROOT']."/netatmo/splNetatmoAPI.php");
//chdir('/netatmo/'); //for refreshtoken api file path
$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, 0);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);
$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret, $refreshtoken);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);

$Cam=$_GET['Cam'];
if (!$Cam) $Cam="Welcome";
$Arg=$_GET['Arg'];
$Arg2=$_GET['Arg2'];
echo $Cam."<br>".$Arg."<br>".$Arg2."<hr>";
switch($Arg)
{
	// ++++++++++++++++++++++++++ PRESENCE +++++++++++++++++++++++++++++
	case 'setMonitoring':	
		//set Camera monitoring on/off
		$monitoring = $_splNetatmo->setMonitoring($Cam, $Arg2);
		//You can always echo answer to check result ok, or error:
		echo "<pre>monitoring:<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	case 'setLightMode':	
		//set Presence floodlight mode (auto, on, off):
		$_splNetatmo->setLightMode($Cam, $Arg2);
		echo "<pre>monitoring:<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	// +++++++++++++++++++++++++ WELCOME SET ++++++++++++++++++++++++++
	// Welcome Personne Pr ente connue
	case 'setPersonAtHome':
		$monitoring = $_splNetatmo->setPersonsAtHome($Arg2);
		echo "<pre>A la maison:<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	// Welcome Personne Absente connue
	case 'setPersonAway':
		$monitoring = $_splNetatmo->setPersonAway($Arg2);	
		echo "<pre>Dehors:<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	// Welcome Maison vide
	case 'setHomeEmpty':
		$monitoring = $_splNetatmo->setHomeEmpty();	
		echo "<pre>Maison Vide:<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	// +++++++++++++++++++++++++ WELCOME GET ++++++++++++++++++++++++++
		
	// Welcome Get Home
	case 'getHome':
		$monitoring = $_splNetatmo->getHomes();	
		echo "<pre>Get Home :<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	
	// Welcome Get Person 
	case 'getPerson':
		$monitoring = $_splNetatmo->getPersons($Arg2);	
		echo "<pre>Get Personne :<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;

	// Welcome Get Persons at Home
	case 'getPersonsAtHome':
		$monitoring = $_splNetatmo->getPersonsAtHome();	
		echo "<pre>Qui est a la maison :<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
		
	case 'isHomeEmpty':
		$monitoring = $_splNetatmo->isHomeEmpty();
		echo "<pre>La maison est vide ? ".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;
	// Welcome Evenements
	case 'getIndoorEvents':
		$monitoring = $_splNetatmo->getIndoorEvents();	
		echo "<pre>Evenements :<br>".json_encode($monitoring, JSON_PRETTY_PRINT)."</pre><br>";
	break;

	// +++++++++++++++++++++++++ DEFAUT +++++++++++++++++++++++++
	
	default :
		// Affiche les caméras Welcome
		$Cameras = $_splNetatmo->getWelcomeCameras();
		echo "<pre>Cameras:<br>".json_encode($Cameras, JSON_PRETTY_PRINT)."</pre><br>";
		// Affiche les caméras Presence
		$Cameras = $_splNetatmo->getPresenceCameras();
		echo "<pre>Cameras:<br>".json_encode($Cameras, JSON_PRETTY_PRINT)."</pre><br>";
}
?>
```

and i call with this url
http://x.x.x.x/netatmo/camera-netatmo.php?Cam=Salon&Arg=setMonitoring&Arg2=on

**Comment by Cadkey** [comment]
@dedelajoie
 then modify the ending like this since you don't have a camera:
 if ($var == true)
 {
 $this->getWeatherDatas();
 // $this->getCameras();
 // $this->getPersons();
 }
 }
 }//splNetatmoAPI end
 ?>
 and you will no longer go through the code that concerns the cameras, only the weather station.

**Comment by Cadkey** [comment]
@dedelajoie
 then in splNetatmo.api modify the ending like this since you don't have a camera:
 if ($var == true)
 {
 $this->getWeatherDatas();
 // $this->getCameras();
 // $this->getPersons();
 }
 }
 }//splNetatmoAPI end
 ?>
 and you will no longer go through the code that concerns the cameras, only the weather station.

**Comment by dedelajoie** [comment]
hello @Cadkey 
it's definitly better cause the script ends without error but I get : 
false 
to the line "$getWeatherModuleDatas = $_splNetatmo->getWeatherModuleDatas('Exterieur');"
I changed "Exterieur" to the name of my module but it still doesn't work

**Comment by Cadkey** [comment]
Does your exterior module communicate via the Netatmo application on your smartphone or on the netatmo web page?
If not, battery problem?

**Comment by dedelajoie** [comment]
yes it does, it works both on the web and on my phone :(

**Comment by loicdeschamps** [comment]
No solution about ID Home ?

**Comment by Cadkey** [comment]
Error is 'HTTP request failed! HTTP/1.1 403 Forbidden'.
Your problem is refresh_token

**Comment by Cadkey** [comment]
@dedelajoie, what is the exact text of the error?

**Comment by dedelajoie** [comment]
there is no real error, it just says "false" after these line : 
$getWeatherModuleDatas = $_splNetatmo->getWeatherModuleDatas('Exterieur');
echo "<pre>getWeatherModuleDatas:<br>".json_encode($getWeatherModuleDatas, JSON_PRETTY_PRINT)."</pre><br>";

I obviously change "Exterieur" with my meteo station (which is "maison")

So for me it doesn't recognize the module "maison".

**Comment by Cadkey** [comment]
But it never worked?  Because what does this have to do with the original topic refresh_token?

**Comment by dedelajoie** [comment]
It did work for a couple of... years 
but for a couple of days I noticed I wasn't retrieving any more data...

**Comment by Cadkey** [comment]
This has nothing to do with refresh_token.  Can't help you anymore.

**Comment by dedelajoie** [comment]
we agree upon the fact that "Exterieur" here has to be replace with the name your module ? 
stupid question : does this have to be your outdoor module ? (cause mine has been dead for years now and I only have the indoor one) 

"$getWeatherModuleDatas = $_splNetatmo->getWeatherModuleDatas('Exterieur');"

**Comment by hax1** [comment]
Indoor works as well

**Comment by dedelajoie** [comment]
oh putain 
so for some reason getWeatherModuleDatas('Exterieur') does not work 

but it turns out that getWeatherTemperatures(); works ! 

I guess there is a problem when the module name is processed.

I don't know much about php but I went through splNetatmoAPI.php and I modified a function so that it displays the json structure of "_weatherDatas"
Here is what I get in the module section : 

                "modules": [
                    {
                        "_id": "XXXXXXXXXX",
                        "type": "NAModule1",
                        "module_name": "Ext\u00e9rieur",
                        "last_setup": 1717670095,
                        "data_type": [
                            "Temperature",
                            "Humidity"
                        ]
                    }
                ]

any idea ? 

(thank you all of you for the time you dedicated to undestand my problem, especially @Cadkey )

**Comment by Cadkey** [comment]
there is nothing to modify in the API.  If your outdoor module is dead, it will not send a temperature via the API.  to get the temperatures from all modules:
 $getWeatherTemperatures = $_splNetatmo->getWeatherTemperatures();

**Comment by Cadkey** [comment]
Because you don't have an additional module, it no longer works, it no longer exists.
here is all the info you can get:
```
$getHomes = $_myNetatmo->getHomes();
	echo 'getHomes:' ."\n" .json_encode($getHomes, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ."\n\n";
	$getWeatherBatteries = $_myNetatmo->getWeatherBatteries();
	echo 'WeatherBatteries:' ."\n" .json_encode($getWeatherBatteries, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ."\n\n";
	$getWeatherTemperatures = $_myNetatmo->getWeatherTemperatures();
	echo 'WeatherTemperatures:' ."\n" .json_encode($getWeatherTemperatures, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ."\n\n";
	$getWeatherStationDatas = $_myNetatmo->getWeatherStationDatas();
	echo 'WeatherStationDatas:' ."\n" .json_encode($getWeatherStationDatas, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ."\n\n";
	$getWeatherModuleDatas = $_myNetatmo->getWeatherModuleDatas('Exterieur');
	echo 'WeatherModuleDatas:' ."\n" .json_encode($getWeatherModuleDatas, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ."\n\n";
```

If you add modules, they will appear in $getHomes, exterior module, rain gauge, legrand plug, netatmo camera... all the products.

**Comment by dedelajoie** [comment]
do you know you're great ? 
thanks you very beaucoup !

**Comment by Cadkey** [comment]
You can buy an exterior module alone: https://shop.netatmo.com/fr-fr/weather/accessories/outdoor-module

**Comment by Cadkey** [comment]
@loicdeschamps Need to clean up your code:

```
<?php
$Netatmo_app_id = 'yyyyyy';
$Netatmo_app_secret= 'zzzzzzzzz';
require($_SERVER['DOCUMENT_ROOT']."/netatmo/splNetatmoAPI.php");
$_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);

$Cam=$_GET['Cam'];
...
```

Use strictly what is indicated in the github, everything works. Put the value of your refresh_token in a refreshtoken.txt file in your script folder, not a mixture of json file in a txt file.

**Comment by loicdeschamps** [comment]
> @loicdeschamps Need to clean up your code:
> 
> ```
> <?php
> $Netatmo_app_id = 'yyyyyy';
> $Netatmo_app_secret= 'zzzzzzzzz';
> require($_SERVER['DOCUMENT_ROOT']."/netatmo/splNetatmoAPI.php");
> $_splNetatmo = new splNetatmoAPI($Netatmo_app_id, $Netatmo_app_secret);
> if (isset($_splNetatmo->error)) die($_splNetatmo->error);
> 
> $Cam=$_GET['Cam'];
> ...
> ```
> 
> Use strictly what is indicated in the github, everything works. Put the value of your refresh_token in a refreshtoken.txt file in your script folder, not a mixture of json file in a txt file.

hi Cadkey

it's works now with your help

thanks you very much

regards
