### ISSUE TITLE
description missing

### ISSUE THREAD

**Issue by mcsteGitHub** [KiboOst/php-simpleNetatmoAPI#2]
Where to fill in "client_id" and "client_secret" within the PHP (what line & where) ?
Can you please be more precise.
Thanks in Advance

**Comment by KiboOst** [comment]
Hi,

Check initialize in the doc

Fill in user/password/id/secret

`$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);`

**Comment by mcsteGitHub** [comment]
Thanks, but obviously I´m not routined enough. I can see the initialize DOC (3 lines of code, right?), but where do I exactly place this string? And where do I fill in "user/password/id/secret"

Could you show me the string with filled in placeholders like: USER / PASSWORD / ID / SECRET.
Thanks in Advance.

**Comment by KiboOst** [comment]
Hi,
You have to create your own php script. In this script, include the class and call it with your user/pass/id/secret, then call any function you want.
Here is a very basic example, with the php class in same folder:

`<?php
require('splNetatmoAPI.php');

$Netatmo_user = 'myemail@whatever.com';
$Netatmo_pass = 'mypass';
$Netatmo_app_id = '55465465465321321';
$Netatmo_app_secret = '56d5f6f5sd6f5s6f':;

$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);

$_splNetatmo->setLightIntensity('myCamera', 100);

?>`

**Comment by mcsteGitHub** [comment]
thanks first for your great support. What I did, and what does not work.

1) I created a file "index.php"
2) Content of "index.php" looking like that ... SEE BELOW ***
3) I did copy both files (" index.php" AND "splNetatmoAPI.php") in same server directory

4) called in browser "index.php" 
- RESULT: empty screen
**- what am I doing wrong ???**


***
`<?php
require('splNetatmoAPI.php');

$Netatmo_user = 'myemail@whatever.com';
$Netatmo_pass = 'mypass';
$Netatmo_app_id = '55465465465321321';
$Netatmo_app_secret = '56d5f6f5sd6f5s6f':;

$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);

echo $_splNetatmo->isHomeEmpty();

?>`

**Comment by KiboOst** [comment]
Try adding this on top of your script:

error_reporting(E_ALL);
ini_set('display_errors', true);

**Comment by mcsteGitHub** [comment]
**What I did**
- added the 2 lines (see below) on top of " index.php" AND "splNetatmoAPI.php"
- **nothing Happens**! Blank browser screen.

`<?php
error_reporting(E_ALL);
ini_set('display_errors', true);
.... `

**ANOTHER NOTE:** 
I´m on a RPI

**I looked into APACHE2 logs** _is this helpful for you?_
192.168.MY.IP - - [17/Jan/2018:17:32:26 +0100] „GET /directorypath/index.php HTTP/1.1“ 500 187 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7"

**Comment by KiboOst** [comment]
Yes because if your home is not empty, it is false and php doesn't echo false.
Sorry but all is in the doc and quite simple php.

Please try this:
`<?php

error_reporting(E_ALL);
ini_set('display_errors', true);

require('splNetatmoAPI.php');

$Netatmo_user = 'myemail@whatever.com';
$Netatmo_pass = 'mypass';
$Netatmo_app_id = '55465465465321321';
$Netatmo_app_secret = '56d5f6f5sd6f5s6f';

$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);
echo '<br>API version: ', $_splNetatmo->_APIversion, "<br>";
if (isset($_splNetatmo->error)) die($_splNetatmo->error);

$var = $_splNetatmo->isHomeEmpty();
echo $var ? 'true' : 'false'."<br>";

?>`

**Comment by mcsteGitHub** [comment]
sooory..... (I had a wrong sign at the end of the Secret key 👎  ... my fault)

**now I get the response:**
API version: 1.31 false

what next? to get it workin ?

**Comment by KiboOst** [comment]
What next ?? It works just fine ! You are running this API version 1.31, and your home is not empty.

Now just use any function you want by looking the doc and do your script according to your need.

**Comment by mcsteGitHub** [comment]
I managed to get Temperature of all Thermometers :)

For Welcome, to "Set a Person away", or anything else. I do not get Responses. 

Do I need ....
- Person ID -> how do they look like? (like: $Netatmo_user = ... )
- Home ID -> how do they look like?

**Comment by mcsteGitHub** [comment]
found it out ...  !!!

- $homeID = '_HOME ID_';
- $personID = '_PERSON ID_';

maybe that´s all ideas to add this to documentation :)
many thanks for now for YOUR GREAT SUPPORT !!!!

**Comment by mcsteGitHub** [comment]
**STILL NO ECHO with** 
`//is home empty ?
echo $_splNetatmo->isHomeEmpty();`

**but RESULT eg. with**
`//get John datas:
$John = $_splNetatmo->getPerson('John');
echo "<pre>John :<br>".json_encode($John , JSON_PRETTY_PRINT)."</pre><br>";`
