### ISSUE TITLE
home empty ... does not work

### ISSUE THREAD

**Issue by mcsteGitHub** [KiboOst/php-simpleNetatmoAPI#3]
STILL NO ECHO with
//is home empty ? echo $_splNetatmo->isHomeEmpty();

**Comment by KiboOst** [comment]
Like I previously said, if your home is not empty, it returns false, which not echoed in php.
Do:
`
$var = $_splNetatmo->isHomeEmpty();

echo $var ? 'true' : 'false'."
`

If you initialize correctly the API like this:

`
$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);

if (isset($_splNetatmo->error)) die($_splNetatmo->error);
`
and have no error, then the API runs fine and you have to do your own script like you want

**Comment by mcsteGitHub** [comment]
**I tried ... and it DID NOT return an ERROR**
`
$_splNetatmo = new splNetatmoAPI($Netatmo_user, $Netatmo_pass, $Netatmo_app_id, $Netatmo_app_secret);
if (isset($_splNetatmo->error)) die($_splNetatmo->error);
`

**I entered these lines*** following ... and the result was:**
- always FALSE !
- irrepective if Home was empty OR people were present
`
$var = $_splNetatmo->isHomeEmpty();
echo $var ? 'true' : 'false'; 
`

*** I think your code was misstypend, right ( ... 'false'."  >  ... 'false'; )

**Comment by mcsteGitHub** [comment]
I´d appreciate your support. I tried everything, but this command seems not work `echo $_splNetatmo->isHomeEmpty();` 

I could also not find the "getPersonsAtHome()  plus the Count" command in the Netatmo Developer Kit (that is defined in your "splNetatmoAPI.php")

**Comment by mcsteGitHub** [comment]
´d appreciate a response

**Comment by KiboOst** [comment]
Several peoples use it everyday for months without problems on such simple functions, so I would double check your code. isHomeEmpty() have always worked, I use it myself and all works great here. Check with your Netatmo app, set home empty and check, set someone at home and check.

Regarding getPersonsAtHome(), this API isn't an exact warper to the official API, but offer more options, like this one which is not in the official API indeed.

**Comment by mcsteGitHub** [comment]
Hi,
truly - any other command works, just that not. What could be the problem? 

Testet again now:
- I copied again the "splNetatmoAPI.php" Version 1.31 in the server
- used the command "echo $_splNetatmo->isHomeEmpty();"
- no response
   - when 1 Person is present (see it when using your PHP .. Who is home ...) 
   - setting Home empty with Netatmo APP
   - setting home empty with your PHP command line

What should actually be the response?
- true
- ???

Another approach ... when home is empty
- when using your PHP "Who is Home"
- and receiving as Output: "{ "result": [] }"
- can´t I use this Output? somehow?

regards & tahnks in Advance for your support

**Comment by KiboOst** [comment]
As I said several times above:

$_splNetatmo->isHomeEmpty() will return true or false. BUT php won't echo false (this is how php works!), but of course you can check it in the code.
example:
`
$empty = $_splNetatmo->isHomeEmpty();
if ($empty) echo 'Home is empty';
else echo 'Home is not empty';
`

**Comment by mcsteGitHub** [comment]
Hi, 
- i checked  with your code above:
-  I always get echoen "Home is Empty"
.... regardless if I set Home Empty with APP, or your PHP .... sorry!

As you see I am not so firm with coding, but is this code really correct (count($atHome)==0)????

I did following Tests:
(1) I set my home empty
(2) I tried to change the code in "splNetatmoAPI.php"
(3) I set my home empty
-  with: (count($atHome)==0) ... I received: **Home is not empty**
-  with: (count($atHome)==1) ... I received: **Home is empty**
-  with: (count($atHome)==2) ... I received: **Home is not empty**

setting Person HOME does not change any of the status!

**Comment by mcsteGitHub** [comment]
Is correct, that wenn HOME is EMPTY and I use your PHP for WHO IS HOME ... I do receive { "result": [] } ???

**Comment by KiboOst** [comment]
if you mean getPersonsAtHome() function, yes indeed.

I will publish a new bugfix for isHomeEmpty() in a few minutes

**Comment by KiboOst** [comment]
Please check 1.32 ;-)

**Comment by mcsteGitHub** [comment]
GREAT STUFF 1.32 (home empty works now :) !!!!
thanks!

**Comment by KiboOst** [comment]
Nice, and sorry for the confusion with php itself !
