### ISSUE TITLE
Settings for recording 

### ISSUE THREAD

**Issue by dawiinci** [KiboOst/php-simpleNetatmoAPI#4]
Is it possible to add the functionality to change the behavior of detected humans or animals (e.g. notify and record or do nothing)?

It seems to work on this version:
https://github.com/damanujan/php-NetatmoCameraAPI

Thanks

**Comment by KiboOst** [comment]
The version you link to is a fork of another api of mine but Netatmo didn’t agree to let it public. On other hand, the official API which simpleNetatmoAPI relys on, doesn’t support this feature so I can’t include it.
