### ISSUE TITLE
function getLightIntensity

### ISSUE THREAD

**Issue by kaloschke** [KiboOst/php-simpleNetatmoAPI#5]
Hi,

thank you very much for this great software.
Is it possible to create a function getLightIntensity? 
Background: i wish to use a remotecontrol to decrease od increase the intensity.

Greetings
Kaloschke

**Comment by KiboOst** [comment]
Hi,
Sorry, this isn't available via the official API, so I can't add it. Write to Netatmo support to ask this function ?
