### ISSUE TITLE
Not an issue, just a thank you

### ISSUE THREAD

**Issue by skyynet** [KiboOst/php-simpleNetatmoAPI#6]
Hi, didn't find a contact address so I just wanted to tell you that your simpleNetatmo API helped me to start with getting data from my Netatmo weather station.

I intend to query my Netatmo data periodically and forward it to OpenWeatherMap as my OpenSprinkler system needs weather data which were transferred to wunderground in the past but Netatmo does no longer support this data transfer. As OpenWeatherMap is also supported I trying to setup a data forwarder on my Synology NAS at home.

**Comment by KiboOst** [comment]
Thanks for your message, always nice to see our work helping others too ;-)
