### ISSUE TITLE
damanujan/php-NetatmoCameraAPI vs KiboOst/php-simpleNetatmoAPI

### ISSUE THREAD

**Issue by jpr105** [KiboOst/php-simpleNetatmoAPI#7]
Bonjour,

D'après ce que je comprends vous avez participé à "php-NetatmoCameraAPI". 
Mon projet est juste de commander le projecteur de ma "Présence" depuis ma Home Center 2 Fibaro comme le fait SIRI via l'application Homekit. Je suis au bon endroit ?

Et merci pour le job accompli !!

Have a good day - Jean-Paul

**Comment by KiboOst** [comment]
Bonjour,

Je n'ai pas _participé_ au développement de php-NetatmoCameraAPI, je l'ai entièrement développé, seul.
Cette API permettait un contrôle total des cameras Netatmo, mais après discussions avec Netatmo ils préféraient qu'elle ne reste pas public.

Concernant le contrôle du projecteur des Presence, utilisez cette API ([php-simpleNetatmoAPI
](https://github.com/KiboOst/php-simpleNetatmoAPI))

Notamment (voir la doc):

//change Presence light intensity:
$_splNetatmo->setLightIntensity('MyCam', 85);

//change Presence Light mode (use either 'auto', 'on', 'off':
$_splNetatmo->setLightMode('MyCam', 'auto');

;-)

**Comment by jpr105** [comment]
OK compris et mille excuses si j'ai mal interprété la ... genèse ;-)

J'avais de toute façon basculé sur php-simpleNetatmo API et suis en train de l'intégrer dans mon système.
Si cela vous intéresse je pourrai vous envoyer un lien vers ma solution une fois terminée (par un autre canal que celui-ci si possible) ?

Merci encore et bon WE
Cordialement - Jean-Paul

**Comment by KiboOst** [comment]
Aucun soucis loin de la :-) Et c’est toujours un plaisir de voir que des devs pour des besoins perso aident d’autres personnes.

**Comment by jpr105** [comment]
OK alors allez jeter un coup d'oeil ici : [https://www.domotique-fibaro.fr/topic/12476-piloter-le-projecteur-de-la-cam%C3%A9ra-%C2%AB%C2%A0pr%C3%A9sence%C2%A0%C2%BB-de-chez-netatmo-depuis-la-home-center/](url)
Cordialement - Jean-Paul

**Comment by jpr105** [comment]
OK alors allez jeter un coup d'oeil ici : [https://www.domotique-fibaro.fr/topic/12476-piloter-le-projecteur-de-la-cam%C3%A9ra-%C2%AB%C2%A0pr%C3%A9sence%C2%A0%C2%BB-de-chez-netatmo-depuis-la-home-center/](https://www.domotique-fibaro.fr/topic/12476-piloter-le-projecteur-de-la-cam%C3%A9ra-%C2%AB%C2%A0pr%C3%A9sence%C2%A0%C2%BB-de-chez-netatmo-depuis-la-home-center/)
Cordialement - Jean-Paul

**Comment by jpr105** [comment]
Bonjour,

Chose promise chose due, voici le post que j'ai publié : https://www.domotique-fibaro.fr/topic/12476-piloter-le-projecteur-de-la-caméra-«%C2%A0présence%C2%A0»-de-chez-netatmo-depuis-la-home-center/

Merci encore et bonne journée - Jean-Paul

Envoyé de mon iPad
