### ISSUE TITLE
Fonction pour récupérer l'intensité lumineuse caméra Presence

### ISSUE THREAD

**Issue by ElYoM** [KiboOst/php-simpleNetatmoAPI#9]
Bonjour,

Serait-il possible d'ajouter une fonction pour récupérer l'intensité lumineuse d'une caméra Presence ?
Ne connaissant pas du tout le PHP, j'ai tout de même tenté de le faire moi-même en me basant sur la fonction getWeatherBatteries mais sans succès...

Merci d'avance.

**Comment by KiboOst** [comment]
Désolé mais on ne peux pas l'utiliser. J'ai la commande et tout ce qu'il faut mais tant que Netatmo ne l'autorise pas elle renvoit 403 forbidden.

**Comment by ElYoM** [comment]
Ok, merci quand même. C'est vraiment un manque dans l'API, c'est dommage. ;)
